version: '3'

services:
  nginx:
    build: .
    container_name: sc_reverse_proxy
    volumes:
      - <DOCKER_VOLUME>:/etc/nginx
    ports:
      - <DOCKER_PORT>

networks:
  default:
    external:
      name: <DOCKER_NETWORK>